DISTNAME=		libfaketime-0.9.10
CATEGORIES=		time
MASTER_SITES=		${MASTER_SITE_GITHUB:=wolfcw/}
GITHUB_PROJECT=		libfaketime
GITHUB_TAG=		v${PKGVERSION_NOREV}

MAINTAINER=		eric@garver.life
LICENSE=		gnu-gpl-v2

USE_TOOLS+=	gmake

INSTALLATION_DIRS=	bin man

.include "../../mk/bsd.pkg.mk"
