DISTNAME=	llama-cpp-0.4.0
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_GITHUB:=ggml-org/}
GITHUB_PROJECT=	llama.cpp
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	eric@garver.life
HOMEPAGE=	https://llama.app/
COMMENT=	LLM inference in C/C++
LICENSE=	mit

USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
